theme: jekyll-theme-minimal
title: GA4GH - Genomic Knowledge Standards
future: true
navigation_categories:
  variant_annotation: Variant Annotation
  variant_representation: Variant Representation
  news: News
  howto: Examples & Guides
